source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '3.2.13'
gem 'pg'
gem 'thin'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails', '2.3.0' # NOTE: ActiveAdmin
gem 'slim-rails'
gem 'bourbon'
gem 'quiet_assets'
gem 'ffaker'
gem 'figaro'
gem 'devise'
gem 'activeadmin'
gem 'simple_form'
gem 'zurb-foundation'
gem 'font-awesome-rails'
gem 'acts-as-taggable-on'
gem 'carrierwave'
gem 'rmagick'
gem 'fog'
gem 'chronic'
gem 'stripe'
gem 'exceptional'